FROM node:18 as client

WORKDIR /usr/src
COPY package.json /usr/src/package.json

RUN yarn install
COPY . /usr/src
RUN yarn build

FROM nginx:latest
COPY --from=client /usr/src/dist /usr/share/nginx/html

EXPOSE 80
