FROM node:latest as client

WORKDIR /usr/src
COPY package.json /usr/src/package.json

RUN npm install
COPY . /usr/src
RUN npm run build

FROM nginx:latest
COPY --from=client /usr/src/dist /usr/share/nginx/html

EXPOSE 80
